### ISSUE TITLE
Why don't use MATLAB regress function 

### ISSUE THREAD

**Issue by fatfishZhao** [panditanvita/BTCpredictor#2]
Why you use Rundeopt for regression.
I think regress function is convenient.
`X=[ones(size(regressorX,1),1),regressorX];
b = regress(regressorY',X);`
The results are the same.

**Comment by panditanvita** [comment]
It's true that Matlab's linear regression-based regress() and the Differential Evolution library both find appropriate weights given a training set and labels. But they use different methods, and I'm not sure how those methods compare in terms of finding good output weights, and computation time required on this dataset. Rundeopt was written by another contributor.

Does regress() do significantly better on either of those?

**Comment by fatfishZhao** [comment]
I didn't check whether their methods are the same, but their outputs are
the same in this problem, and MATLAB regress () is much quicker on your
data, you can have a try. I will check their methods later.

2017年5月31日 上午11:40，"Anvita Pandit" <notifications@github.com>写道：

It's true that Matlab's linear regression-based regress() and the
Differential Evolution library both find appropriate weights given a
training set and labels. But they use different methods, and I'm not sure
how those methods compare in terms of finding good output weights, and
computation time required on this dataset. Rundeopt was written by another
contributor.

Does regress() do significantly better on either of those?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/panditanvita/BTCpredictor/issues/2#issuecomment-305073540>,
or mute the thread

**Comment by panditanvita** [comment]
Feel free to submit a pull request for it
