### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by TZJinzo** [panditanvita/BTCpredictor#5]
Is this still active? Also, out of curiosity, after reading the paper, it looks like this was only done on a few hundred dollars. Can the same returns be reproduced for hundreds of thousands of $? If there is a possibility, or if by chance you manage to read this, I would be interested in having a chat about developing this algorithm further with a much larger sum of money.

**Comment by panditanvita** [comment]
At the time of the paper, total market cap of Bitcoin was relatively small, and orders upwards of a thousand dollars would have been large enough to shift the market. Market cap has vastly increased since then and larger orders are now possible. 
 
We have a slack channel. Email me.

**Comment by danieltidus** [comment]
Hi,

Slack channel still up? Please, if ok add me. (danieltidus@gmail.com)

**Comment by panditanvita** [comment]
Here you go - 30 day open link for anyone else who is curious.
https://join.slack.com/t/btcpredictor/shared_invite/enQtMjk2MjQwODQ4NTgzLWM1ZjcyZDNkYWY5Yzk5NDllNTIwNjllNmZmMjFhNWRmMTc4OWY1Y2MxMDA2NDVmZWFjODYxMDdjMDZjYWNlOWU

Make sure you read the FAQ on Github and previous comments before asking
questions!
